language: elixir
otp_release:
  - 20.1
  - 20.0
  - 19.2
    # - 19.1
  - 19.0
  - 18.3
  # - 18.2
  # - 18.1
  - 18.0
elixir:
  # - 1.6.0
  - 1.5.2
  # - 1.5.1
  - 1.5.0
branches:
  only:
    - master
    - development
env:
  global:
    - MIX_ENV=test
    - DOCTESTS=true
    - ALL_BACKENDS=true
    - GITHUB_ACCESS=$GITHUB_ACCESS_TOKEN
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix clean
  - mix compile
stages:
  - name: test
  - name: docs
  - name: style
  - if: (type = pull_request OR branch = master) AND env(GITHUB_ACCESS) IS present
  - name: types
  - if: type != pull_request
jobs:
  include:
    - stage: test
    - script:
      - mix coveralls
    - stage: docs
    - script:
      - mix inch.report
    - stage: style
    - script:
      - rvm install ruby-2.3.1
      - gem install pronto-credo
      - pronto run -f github_status github_pr_review
    - stage: types
    - script:
      - mix dialyzer --halt-exit-status
services:
  - redis-server
  - memcached
  - elasticsearch
cache:
  directories:
    - "/home/travis/.rvm/"
    - _build
    - deps
