language: elixir
otp_release:
  - 20.1
  - 20.0
  - 19.2
    # - 19.1
  - 19.0
  - 18.3
  # - 18.2
  # - 18.1
  - 18.0
elixir:
  # - 1.6.0
  - 1.5.2
  # - 1.5.1
  - 1.5.0
branches:
  only:
    - master
    - development
env:
  global:
    - MIX_ENV=test
    - DOCTESTS=true
    - ALL_BACKENDS=true
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix clean
  - mix compile
script: mix coveralls
stages:
  - name: checks
  - name: test
jobs:
  include:
    - stage: checks
    - script: mix credo list
    - script: mix dialyzer --halt-exit-status
    - script: mix inch.report
    - stage: test
services:
  - redis-server
  - memcached
  - elasticsearch
cache:
  directories:
    - "/home/travis/.rvm/"
    - _build
    - deps
