# TESTS
script: mix coveralls.travis
stages:
  - name: checks
  - name: test
jobs:
  include:
    - stage: checks
    - script: mix credo list
    - script: travis_wait mix dialyzer --check=false
    - script: mix inch.report
    
    - stage: test

# MATRIX
language: elixir
otp_release:
  - 20.1
  - 20.0
  - 19.2
    # - 19.1
  - 19.0
  - 18.3
  # - 18.2
  # - 18.1
  - 18.0
elixir:
  # - 1.6.0
  - 1.5.2
  # - 1.5.1
  - 1.5.0
os:
  - linux
  # - osx
  # - windows
branches:
  only:
    - master
    - development

# SETUP
env:
  global:
    - MIX_ENV=test
    - DOCTESTS=true
    - ALL_BACKENDS=true
install:
  - sudo apt-get -y install inotify-tools # for cortex
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
services:
  - redis-server
  - memcached
  - elasticsearch

# CACHING
cache:
  directories:
    - deps
    - "/home/travis/.rvm"
    - "/home/travis/.cache"
